version: '3.3'
services:

  tyk-plugin-compiler:
    image: tykio/tyk-plugin-compiler:v4.0.3

  tyk-gateway:
    image: tykio/tyk-gateway:v4.0.3
    depends_on:
      - tyk-mongo
      - tyk-redis
    ports:
      - "8080:8080"
    volumes:
      - ./tyk/bundle:/opt/tyk-gateway/bundle
      - ./tyk/middleware:/opt/tyk-gateway/middleware
    env_file:
      - ./tyk/confs/tyk.env
    networks:
      - tyk

  tyk-pump:
    image: tykio/tyk-pump-docker-pub:v1.6.0
    depends_on:
      - tyk-gateway
      - tyk-mongo
      - tyk-redis
    env_file:
      - ./tyk/confs/pump.env
    networks:
      - tyk

  tyk-dashboard:
    image: tykio/tyk-dashboard:v4.0.3
    depends_on:
      - tyk-gateway
      - tyk-pump
    ports:
      - "3000:3000"
      - "5000:5000"
    env_file:
      - ./tyk/confs/tyk_analytics.env
    networks:
      - tyk

  tyk-mongo:
    image: mongo:3.2
    command: [ "mongod", "--smallfiles" ]
    ports:
      - "27017:27017"
    volumes:
      - tyk-mongo-data:/data/db
    networks:
      - tyk

  tyk-redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - tyk-redis-data:/data
    networks:
      - tyk

volumes:
  tyk-mongo-data:
  tyk-redis-data:

networks:
  tyk:
